import mongoose from "mongoose";

const futureRaceSchema = new mongoose.Schema(
  {
    race_id: { type: String, required: true, unique: true, index: true },
    course: String,
    course_id: String,
    date: { type: String, required: true }, // e.g., "2025-05-12"
    off_time: String,
    off_dt: Date,
    race_name: String,
    distance_round: String,
    distance: String,
    distance_f: Number,
    region: String,
    pattern: String,
    sex_restriction: String,
    race_class: String,
    type: String,
    age_band: String,
    rating_band: String,
    prize: String,
    field_size: String,
    going_detailed: String,
    rail_movements: String,
    stalls: String,
    weather: String,
    going: String,
    surface: String,
    jumps: String,
    big_race: { type: Boolean, default: false },
    is_abandoned: { type: Boolean, default: false },
    tip: String,
    verdict: String,
    betting_forecast: String,
    runners: [
      {
        horse_id: String,
        horse: String,
        dob: String,
        age: String,
        sex: String,
        sex_code: String,
        colour: String,
        region: String,
        breeder: String,
        dam: String,
        dam_id: String,
        dam_region: String,
        sire: String,
        sire_id: String,
        sire_region: String,
        damsire: String,
        damsire_id: String,
        damsire_region: String,
        trainer: String,
        trainer_id: String,
        trainer_location: String,
        trainer_14_days: {
          type: mongoose.Schema.Types.Mixed,
          default: {},
        },
        owner: String,
        owner_id: String,
        prev_trainers: {
          type: [mongoose.Schema.Types.Mixed],
          default: [],
        },
        prev_owners: {
          type: [mongoose.Schema.Types.Mixed],
          default: [],
        },
        comment: String,
        spotlight: String,
        quotes: {
          type: [mongoose.Schema.Types.Mixed],
          default: [],
        },
        stable_tour: {
          type: [mongoose.Schema.Types.Mixed],
          default: [],
        },
        medical: {
          type: [mongoose.Schema.Types.Mixed],
          default: [],
        },
        number: String,
        draw: String,
        headgear: String,
        headgear_run: String,
        wind_surgery: String,
        wind_surgery_run: String,
        past_results_flags: {
          type: [mongoose.Schema.Types.Mixed],
          default: [],
        },
        lbs: String,
        ofr: String,
        rpr: String,
        ts: String,
        jockey: String,
        jockey_id: String,
        silk_url: String,
        last_run: String,
        form: String,
        trainer_rtf: String,
        odds: {
          type: [mongoose.Schema.Types.Mixed],
          default: [],
        },
      },
    ],
  },
  { timestamps: true }
);

export default mongoose.model("future_race", futureRaceSchema);
